// <auto-generated />
namespace ReplayFXSchedule.Web.Migrations.ReplayFXDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EventMenu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventMenu));
        
        string IMigrationMetadata.Id
        {
            get { return "202205111815297_EventMenu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
