// <auto-generated />
namespace ReplayFXSchedule.Web.Migrations.ReplayFXDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddFCM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFCM));
        
        string IMigrationMetadata.Id
        {
            get { return "202411150252007_AddFCM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
